# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  bench:
    desc: run all benchmarks
    cmd: "go test -bench . ./..."
  cli:
    desc: run the CLI
    dir: "./cmd/taskkit/"
    cmd: "go run . {{.CLI_ARGS}}"
    env:
      DEVEL: true
      TASKKIT_CONFIG: ./testdata/config.yaml
  cli-install:
    desc: install the CLI
    dir: "./cmd/taskkit/"
    cmd: "go install ."
  codegen:
    desc: run codegen
    cmds:
      - "sqlc generate"
  test:
    desc: run all tests
    cmd: "go test ./..."
  release-snapshot:
    desc: release (no push)
    cmd: "goreleaser --snapshot --clean"
  release:
    prompt: "Release {{.NEXT_RELEASE}}?"
    desc: release (no push)
    env:
      GITHUB_TOKEN: "$(gh auth token)"
    vars:
      NEXT_RELEASE:
        sh: "svu next"
    preconditions:
      - "which gh"
      - "which git"
      - "which goreleaser"
      - "which svu"
    cmds:
      - "git tag {{.NEXT_RELEASE}}"
      - "git push origin $(svu current)"
      - "goreleaser release --clean"
