// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package db

import (
	"context"
)

const deleteDependenciesByTaskID = `-- name: DeleteDependenciesByTaskID :exec
DELETE FROM task_dependencies WHERE task_id = ? OR depends_on = ?
`

type DeleteDependenciesByTaskIDParams struct {
	TaskID    string
	DependsOn string
}

func (q *Queries) DeleteDependenciesByTaskID(ctx context.Context, arg DeleteDependenciesByTaskIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesByTaskID, arg.TaskID, arg.DependsOn)
	return err
}

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM task_dependencies WHERE task_id = ? AND depends_on = ?
`

type DeleteDependencyParams struct {
	TaskID    string
	DependsOn string
}

func (q *Queries) DeleteDependency(ctx context.Context, arg DeleteDependencyParams) error {
	_, err := q.db.ExecContext(ctx, deleteDependency, arg.TaskID, arg.DependsOn)
	return err
}

const getActiveBlockedByTaskID = `-- name: GetActiveBlockedByTaskID :many
SELECT td.depends_on
FROM task_dependencies td
JOIN tasks t ON t.task_id = td.depends_on
WHERE td.task_id = ?
  AND t.status IN ('pending', 'waiting')
ORDER BY td.depends_on
`

// Returns task IDs of blockers that are still active (pending or waiting).
func (q *Queries) GetActiveBlockedByTaskID(ctx context.Context, taskID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBlockedByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var depends_on string
		if err := rows.Scan(&depends_on); err != nil {
			return nil, err
		}
		items = append(items, depends_on)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveBlockingTaskID = `-- name: GetActiveBlockingTaskID :many
SELECT td.task_id
FROM task_dependencies td
JOIN tasks t ON t.task_id = td.task_id
WHERE td.depends_on = ?
  AND t.status IN ('pending', 'waiting')
ORDER BY td.task_id
`

// Returns task IDs of dependents that are still active (pending or waiting).
func (q *Queries) GetActiveBlockingTaskID(ctx context.Context, dependsOn string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBlockingTaskID, dependsOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var task_id string
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockedByTaskID = `-- name: GetBlockedByTaskID :many
SELECT depends_on FROM task_dependencies WHERE task_id = ? ORDER BY depends_on
`

// Returns all task IDs that block the given task (regardless of status).
func (q *Queries) GetBlockedByTaskID(ctx context.Context, taskID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockedByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var depends_on string
		if err := rows.Scan(&depends_on); err != nil {
			return nil, err
		}
		items = append(items, depends_on)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockingTaskID = `-- name: GetBlockingTaskID :many
SELECT task_id FROM task_dependencies WHERE depends_on = ? ORDER BY task_id
`

// Returns all task IDs that the given task blocks (regardless of status).
func (q *Queries) GetBlockingTaskID(ctx context.Context, dependsOn string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockingTaskID, dependsOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var task_id string
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDependency = `-- name: InsertDependency :exec
INSERT INTO task_dependencies (task_id, depends_on) VALUES (?, ?)
`

type InsertDependencyParams struct {
	TaskID    string
	DependsOn string
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertDependency, arg.TaskID, arg.DependsOn)
	return err
}
