// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package db

import (
	"context"
	"database/sql"
)

const getHistoryByOperationID = `-- name: GetHistoryByOperationID :many
SELECT id, operation_id, task_id, "action", field, old_value, new_value FROM history WHERE operation_id = ? ORDER BY id
`

func (q *Queries) GetHistoryByOperationID(ctx context.Context, operationID string) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByOperationID, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.TaskID,
			&i.Action,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryByTaskID = `-- name: GetHistoryByTaskID :many
SELECT id, operation_id, task_id, "action", field, old_value, new_value FROM history WHERE task_id = ? ORDER BY id
`

func (q *Queries) GetHistoryByTaskID(ctx context.Context, taskID string) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.TaskID,
			&i.Action,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestHistoryForTask = `-- name: GetLatestHistoryForTask :one
SELECT id, operation_id, task_id, "action", field, old_value, new_value FROM history WHERE task_id = ? ORDER BY id DESC LIMIT 1
`

// Returns the most recent history row for a task; used to derive modified time.
func (q *Queries) GetLatestHistoryForTask(ctx context.Context, taskID string) (History, error) {
	row := q.db.QueryRowContext(ctx, getLatestHistoryForTask, taskID)
	var i History
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.TaskID,
		&i.Action,
		&i.Field,
		&i.OldValue,
		&i.NewValue,
	)
	return i, err
}

const getLatestOperationID = `-- name: GetLatestOperationID :one
SELECT operation_id FROM history ORDER BY id DESC LIMIT 1
`

// Returns the operation_id of the most recent operation, for use by undo.
func (q *Queries) GetLatestOperationID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestOperationID)
	var operation_id string
	err := row.Scan(&operation_id)
	return operation_id, err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO history (operation_id, task_id, action, field, old_value, new_value)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertHistoryParams struct {
	OperationID string
	TaskID      string
	Action      string
	Field       sql.NullString
	OldValue    sql.NullString
	NewValue    sql.NullString
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory,
		arg.OperationID,
		arg.TaskID,
		arg.Action,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}
