// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type History struct {
	ID          int64
	OperationID string
	TaskID      string
	Action      string
	Field       sql.NullString
	OldValue    sql.NullString
	NewValue    sql.NullString
}

type Task struct {
	TaskID      string
	DisplayID   int64
	Project     sql.NullString
	Description string
	Status      string
	Deadline    sql.NullString
	Scheduled   sql.NullString
	Wait        sql.NullString
}

type TaskDependency struct {
	TaskID    string
	DependsOn string
}

type TaskTag struct {
	TaskID string
	Tag    string
}
