// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM task_tags WHERE task_id = ? AND tag = ?
`

type DeleteTagParams struct {
	TaskID string
	Tag    string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.TaskID, arg.Tag)
	return err
}

const deleteTagsByTaskID = `-- name: DeleteTagsByTaskID :exec
DELETE FROM task_tags WHERE task_id = ?
`

func (q *Queries) DeleteTagsByTaskID(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByTaskID, taskID)
	return err
}

const getTagsByTaskID = `-- name: GetTagsByTaskID :many
SELECT tag FROM task_tags WHERE task_id = ? ORDER BY tag
`

func (q *Queries) GetTagsByTaskID(ctx context.Context, taskID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO task_tags (task_id, tag) VALUES (?, ?)
`

type InsertTagParams struct {
	TaskID string
	Tag    string
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag, arg.TaskID, arg.Tag)
	return err
}
