// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (task_id, display_id, project, description, status, deadline, scheduled, wait)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	TaskID      string
	DisplayID   int64
	Project     sql.NullString
	Description string
	Status      string
	Deadline    sql.NullString
	Scheduled   sql.NullString
	Wait        sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.TaskID,
		arg.DisplayID,
		arg.Project,
		arg.Description,
		arg.Status,
		arg.Deadline,
		arg.Scheduled,
		arg.Wait,
	)
	return err
}

const getActiveDisplayIDs = `-- name: GetActiveDisplayIDs :many
SELECT display_id FROM tasks
WHERE status IN ('pending', 'waiting')
`

func (q *Queries) GetActiveDisplayIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDisplayIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var display_id int64
		if err := rows.Scan(&display_id); err != nil {
			return nil, err
		}
		items = append(items, display_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT task_id, display_id, project, description, status, deadline, scheduled, wait FROM tasks WHERE task_id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, taskID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.DisplayID,
		&i.Project,
		&i.Description,
		&i.Status,
		&i.Deadline,
		&i.Scheduled,
		&i.Wait,
	)
	return i, err
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT task_id, display_id, project, description, status, deadline, scheduled, wait FROM tasks
WHERE status IN ('pending', 'waiting')
ORDER BY task_id
`

func (q *Queries) ListActiveTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.DisplayID,
			&i.Project,
			&i.Description,
			&i.Status,
			&i.Deadline,
			&i.Scheduled,
			&i.Wait,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskDeadline = `-- name: UpdateTaskDeadline :exec
UPDATE tasks SET deadline = ? WHERE task_id = ?
`

type UpdateTaskDeadlineParams struct {
	Deadline sql.NullString
	TaskID   string
}

func (q *Queries) UpdateTaskDeadline(ctx context.Context, arg UpdateTaskDeadlineParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDeadline, arg.Deadline, arg.TaskID)
	return err
}

const updateTaskDescription = `-- name: UpdateTaskDescription :exec
UPDATE tasks SET description = ? WHERE task_id = ?
`

type UpdateTaskDescriptionParams struct {
	Description string
	TaskID      string
}

func (q *Queries) UpdateTaskDescription(ctx context.Context, arg UpdateTaskDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDescription, arg.Description, arg.TaskID)
	return err
}

const updateTaskDisplayID = `-- name: UpdateTaskDisplayID :exec
UPDATE tasks SET display_id = ? WHERE task_id = ?
`

type UpdateTaskDisplayIDParams struct {
	DisplayID int64
	TaskID    string
}

func (q *Queries) UpdateTaskDisplayID(ctx context.Context, arg UpdateTaskDisplayIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDisplayID, arg.DisplayID, arg.TaskID)
	return err
}

const updateTaskProject = `-- name: UpdateTaskProject :exec
UPDATE tasks SET project = ? WHERE task_id = ?
`

type UpdateTaskProjectParams struct {
	Project sql.NullString
	TaskID  string
}

func (q *Queries) UpdateTaskProject(ctx context.Context, arg UpdateTaskProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskProject, arg.Project, arg.TaskID)
	return err
}

const updateTaskScheduled = `-- name: UpdateTaskScheduled :exec
UPDATE tasks SET scheduled = ? WHERE task_id = ?
`

type UpdateTaskScheduledParams struct {
	Scheduled sql.NullString
	TaskID    string
}

func (q *Queries) UpdateTaskScheduled(ctx context.Context, arg UpdateTaskScheduledParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskScheduled, arg.Scheduled, arg.TaskID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ? WHERE task_id = ?
`

type UpdateTaskStatusParams struct {
	Status string
	TaskID string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.TaskID)
	return err
}

const updateTaskWait = `-- name: UpdateTaskWait :exec
UPDATE tasks SET wait = ? WHERE task_id = ?
`

type UpdateTaskWaitParams struct {
	Wait   sql.NullString
	TaskID string
}

func (q *Queries) UpdateTaskWait(ctx context.Context, arg UpdateTaskWaitParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskWait, arg.Wait, arg.TaskID)
	return err
}
